
doughter: ./sources/doughter.c
	gcc ./sources/doughter.c -ID:/googleDrive/c/my_libs/libmy_lib -LD:\googleDrive\c\my_libs -lmy_lib -o doughter
parent: ./sources/parent.c
	gcc ./sources/parent.c -ID:/googleDrive/c/my_libs/libmy_lib -LD:\googleDrive\c\my_libs -lmy_lib -o parent